function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import timer
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -1000000; // objWorld
	global.__objectDepths[1] = 0; // objCamera
	global.__objectDepths[2] = 0; // objSmoothCamera
	global.__objectDepths[3] = 0; // objPlayMusic
	global.__objectDepths[4] = 0; // objTitleMenu
	global.__objectDepths[5] = 0; // objDifficultyMenu
	global.__objectDepths[6] = 0; // objOptionsMenu
	global.__objectDepths[7] = 0; // objKeyboardControlsMenu
	global.__objectDepths[8] = 0; // objControllerMenu
	global.__objectDepths[9] = -10; // objPlayerStart
	global.__objectDepths[10] = -10; // objPlayer
	global.__objectDepths[11] = -11; // objBow
	global.__objectDepths[12] = -1; // objBullet
	global.__objectDepths[13] = 0; // objBloodEmitter
	global.__objectDepths[14] = -10; // objBlood
	global.__objectDepths[15] = -100; // objGameOver
	global.__objectDepths[16] = 100; // objBlock
	global.__objectDepths[17] = 100; // objMiniBlock
	global.__objectDepths[18] = 100; // objSlipBlock
	global.__objectDepths[19] = 0; // objBlockInvis
	global.__objectDepths[20] = 0; // objBlockFake
	global.__objectDepths[21] = 100; // objSlideBlock
	global.__objectDepths[22] = 100; // objSlideBlockL
	global.__objectDepths[23] = 100; // objSlideBlockR
	global.__objectDepths[24] = 1; // objBossBlock
	global.__objectDepths[25] = 0; // objSaveBlocker
	global.__objectDepths[26] = 100; // objSlope
	global.__objectDepths[27] = 100; // objSlopeDownLeft
	global.__objectDepths[28] = 100; // objSlopeDownRight
	global.__objectDepths[29] = 100; // objSlopeUpLeft
	global.__objectDepths[30] = 100; // objSlopeUpRight
	global.__objectDepths[31] = 1; // objPlatform
	global.__objectDepths[32] = 1; // objMovingPlatform
	global.__objectDepths[33] = 1; // objMovingPlatformNoBounce
	global.__objectDepths[34] = 1; // objBlockRise
	global.__objectDepths[35] = 1; // objBlockFall
	global.__objectDepths[36] = 0; // objPlayerKiller
	global.__objectDepths[37] = 10; // objSpikeUp
	global.__objectDepths[38] = 10; // objSpikeRight
	global.__objectDepths[39] = 10; // objSpikeLeft
	global.__objectDepths[40] = 10; // objSpikeDown
	global.__objectDepths[41] = 10; // objMiniUp
	global.__objectDepths[42] = 10; // objMiniRight
	global.__objectDepths[43] = 10; // objMiniLeft
	global.__objectDepths[44] = 10; // objMiniDown
	global.__objectDepths[45] = 0; // objCherry
	global.__objectDepths[46] = 0; // objCherryBounce
	global.__objectDepths[47] = 0; // objCherryBounceRandom
	global.__objectDepths[48] = 0; // objCherryBounceLat
	global.__objectDepths[49] = 0; // objCherryBounceVert
	global.__objectDepths[50] = 0; // objKillerBlock
	global.__objectDepths[51] = 0; // objCherryEnemyTest
	global.__objectDepths[52] = 0; // objCherryBossTest
	global.__objectDepths[53] = 10; // objMiku
	global.__objectDepths[54] = 0; // objCherryRandomCol
	global.__objectDepths[55] = 0; // objCherryRandomColExplode
	global.__objectDepths[56] = 0; // objCherryRandomColBounce
	global.__objectDepths[57] = 0; // objFreeTrigger
	global.__objectDepths[58] = 0; // objTriggerButton
	global.__objectDepths[59] = 0; // objKillerTrigger
	global.__objectDepths[60] = 10; // objSpikeTriggerUp
	global.__objectDepths[61] = 10; // objSpikeTriggerRight
	global.__objectDepths[62] = 10; // objSpikeTriggerLeft
	global.__objectDepths[63] = 10; // objSpikeTriggerDown
	global.__objectDepths[64] = 0; // objCherryTrigger
	global.__objectDepths[65] = -50; // objWater
	global.__objectDepths[66] = -50; // objWater2
	global.__objectDepths[67] = -50; // objWater3
	global.__objectDepths[68] = 11; // objWalljumpR
	global.__objectDepths[69] = 11; // objWalljumpL
	global.__objectDepths[70] = 0; // objJumpRefresher
	global.__objectDepths[71] = 10; // objSign
	global.__objectDepths[72] = 0; // objGravityUp
	global.__objectDepths[73] = 0; // objGravityDown
	global.__objectDepths[74] = 1; // objSaveMedium
	global.__objectDepths[75] = 1; // objSave
	global.__objectDepths[76] = 1; // objSaveVHard
	global.__objectDepths[77] = 1; // objSaveMediumFlip
	global.__objectDepths[78] = 1; // objSaveFlip
	global.__objectDepths[79] = 1; // objSaveVHardFlip
	global.__objectDepths[80] = 0; // objWarpStart
	global.__objectDepths[81] = 10; // objRoomChanger
	global.__objectDepths[82] = 0; // objWarp
	global.__objectDepths[83] = 0; // objWarpNext
	global.__objectDepths[84] = 0; // objWarpAutosaveNext
	global.__objectDepths[85] = 10; // objOutsideRoomChanger
	global.__objectDepths[86] = 0; // objSecretItem
	global.__objectDepths[87] = 0; // objSecretIndicator
	global.__objectDepths[88] = 0; // objBossItem
	global.__objectDepths[89] = 0; // objBossIndicator
	global.__objectDepths[90] = 0; // objGameClear


	global.__objectNames[0] = "objWorld";
	global.__objectNames[1] = "objCamera";
	global.__objectNames[2] = "objSmoothCamera";
	global.__objectNames[3] = "objPlayMusic";
	global.__objectNames[4] = "objTitleMenu";
	global.__objectNames[5] = "objDifficultyMenu";
	global.__objectNames[6] = "objOptionsMenu";
	global.__objectNames[7] = "objKeyboardControlsMenu";
	global.__objectNames[8] = "objControllerMenu";
	global.__objectNames[9] = "objPlayerStart";
	global.__objectNames[10] = "objPlayer";
	global.__objectNames[11] = "objBow";
	global.__objectNames[12] = "objBullet";
	global.__objectNames[13] = "objBloodEmitter";
	global.__objectNames[14] = "objBlood";
	global.__objectNames[15] = "objGameOver";
	global.__objectNames[16] = "objBlock";
	global.__objectNames[17] = "objMiniBlock";
	global.__objectNames[18] = "objSlipBlock";
	global.__objectNames[19] = "objBlockInvis";
	global.__objectNames[20] = "objBlockFake";
	global.__objectNames[21] = "objSlideBlock";
	global.__objectNames[22] = "objSlideBlockL";
	global.__objectNames[23] = "objSlideBlockR";
	global.__objectNames[24] = "objBossBlock";
	global.__objectNames[25] = "objSaveBlocker";
	global.__objectNames[26] = "objSlope";
	global.__objectNames[27] = "objSlopeDownLeft";
	global.__objectNames[28] = "objSlopeDownRight";
	global.__objectNames[29] = "objSlopeUpLeft";
	global.__objectNames[30] = "objSlopeUpRight";
	global.__objectNames[31] = "objPlatform";
	global.__objectNames[32] = "objMovingPlatform";
	global.__objectNames[33] = "objMovingPlatformNoBounce";
	global.__objectNames[34] = "objBlockRise";
	global.__objectNames[35] = "objBlockFall";
	global.__objectNames[36] = "objPlayerKiller";
	global.__objectNames[37] = "objSpikeUp";
	global.__objectNames[38] = "objSpikeRight";
	global.__objectNames[39] = "objSpikeLeft";
	global.__objectNames[40] = "objSpikeDown";
	global.__objectNames[41] = "objMiniUp";
	global.__objectNames[42] = "objMiniRight";
	global.__objectNames[43] = "objMiniLeft";
	global.__objectNames[44] = "objMiniDown";
	global.__objectNames[45] = "objCherry";
	global.__objectNames[46] = "objCherryBounce";
	global.__objectNames[47] = "objCherryBounceRandom";
	global.__objectNames[48] = "objCherryBounceLat";
	global.__objectNames[49] = "objCherryBounceVert";
	global.__objectNames[50] = "objKillerBlock";
	global.__objectNames[51] = "objCherryEnemyTest";
	global.__objectNames[52] = "objCherryBossTest";
	global.__objectNames[53] = "objMiku";
	global.__objectNames[54] = "objCherryRandomCol";
	global.__objectNames[55] = "objCherryRandomColExplode";
	global.__objectNames[56] = "objCherryRandomColBounce";
	global.__objectNames[57] = "objFreeTrigger";
	global.__objectNames[58] = "objTriggerButton";
	global.__objectNames[59] = "objKillerTrigger";
	global.__objectNames[60] = "objSpikeTriggerUp";
	global.__objectNames[61] = "objSpikeTriggerRight";
	global.__objectNames[62] = "objSpikeTriggerLeft";
	global.__objectNames[63] = "objSpikeTriggerDown";
	global.__objectNames[64] = "objCherryTrigger";
	global.__objectNames[65] = "objWater";
	global.__objectNames[66] = "objWater2";
	global.__objectNames[67] = "objWater3";
	global.__objectNames[68] = "objWalljumpR";
	global.__objectNames[69] = "objWalljumpL";
	global.__objectNames[70] = "objJumpRefresher";
	global.__objectNames[71] = "objSign";
	global.__objectNames[72] = "objGravityUp";
	global.__objectNames[73] = "objGravityDown";
	global.__objectNames[74] = "objSaveMedium";
	global.__objectNames[75] = "objSave";
	global.__objectNames[76] = "objSaveVHard";
	global.__objectNames[77] = "objSaveMediumFlip";
	global.__objectNames[78] = "objSaveFlip";
	global.__objectNames[79] = "objSaveVHardFlip";
	global.__objectNames[80] = "objWarpStart";
	global.__objectNames[81] = "objRoomChanger";
	global.__objectNames[82] = "objWarp";
	global.__objectNames[83] = "objWarpNext";
	global.__objectNames[84] = "objWarpAutosaveNext";
	global.__objectNames[85] = "objOutsideRoomChanger";
	global.__objectNames[86] = "objSecretItem";
	global.__objectNames[87] = "objSecretIndicator";
	global.__objectNames[88] = "objBossItem";
	global.__objectNames[89] = "objBossIndicator";
	global.__objectNames[90] = "objGameClear";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
